[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# gas_reports = ["MyContract", "MyContractFactory"]
# gas_reports = ["*"]
gas_reports = ["Counter"]


optimizer = true
optimizer_runs = 2_000_000


solc = "0.8.17"
# solc_version = '0.8.17'

# gas_reports_ignore = ["Example"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@solmate-utils/=lib/solmate/src/utils/",
]

