[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 2_000_000
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solmate-utils/=lib/solmate/src/utils/",
    "ds-test/=lib/solmate/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/"
]